<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class candidate extends Model{
public function computer(){ return $this->belongsTo('App\Models\computer'); }
public function report(){ return $this->belongsTo('App\Models\report'); }
}