<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class computer extends Model{
public function candidates(){ return $this->hasMany('App\Models\candidate'); }
public function electors(){ return $this->hasMany('App\Models\elector'); }
public function report(){ return $this->belongsTo('App\Models\report'); }
}