<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class elector extends Model{
    public function computer(){ return $this->belongsTo('App\Models\computer'); }
}
