<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class report extends Model{
public function candidates(){ return $this->hasMany('App\Models\candidate'); }
public function computer(){ return $this->hasOne('App\Models\computer'); }
}